local palette = {
  bg = { gui = 'NONE', cterm = 'NONE' },
  fg = { gui = '#ffffff', cterm = 'White' },
  black = { gui = '#000000', cterm = 'Black' },
  red = { gui = '#ff6060', cterm = 'Red' },
  green = { gui = '#60ff60', cterm = 'Green' },
  yellow = { gui = '#ffff60', cterm = 'Yellow' },
  blue = { gui = '#00bbff', cterm = 'Blue' },
  magenta = { gui = '#ff90ff', cterm = 'Magenta' },
  cyan = { gui = '#00ffff', cterm = 'Cyan' },
  white = { gui = '#ffffff', cterm = 'White' },
  gray = { gui = '#909090', cterm = 'Gray' },
  orange = { gui = '#ffa500', cterm = 'DarkYellow' },
  menu_bg = { gui = '#202020', cterm = 'Black' },
  menu_bg_alt = { gui = '#242424', cterm = 'Black' },
  search_bg = { gui = '#dadada', cterm = 'White' },
  selection_bg = { gui = '#444444', cterm = 'DarkGray' },
  added_bg = { gui = '#00381f', cterm = 'DarkGreen' },
  added_fg = { gui = '#a0e0a0', cterm = 'Black' },
  changed_bg = { gui = '#004065', cterm = 'DarkBlue' },
  changed_fg = { gui = '#b9c6e0', cterm = 'Black' },
  removed_bg = { gui = '#4f1119', cterm = 'DarkRed' },
  removed_fg = { gui = '#ffbfbf', cterm = 'Black' },
  comment_fg = { gui = '#80a0ff', cterm = 'DarkBlue' },
  error_bg = { gui = '#ff0000', cterm = 'DarkRed' },
  non_text_fg = { gui = '#0000ff', cterm = 'DarkBlue' },
}

local function hl(fg, bg, opts)
  local result = {}
  if fg then
    result.fg = palette[fg].gui
    result.ctermfg = palette[fg].cterm
  end
  if bg then
    result.bg = palette[bg].gui
    result.ctermbg = palette[bg].cterm
  end
  if opts and opts.sp then
    opts.sp = palette[opts.sp].gui
  end
  return vim.tbl_extend('force', result, opts or {})
end

local groups = {
  ColorColumn = hl(nil, 'selection_bg'),
  Conceal = hl('gray'),
  CurSearch = hl('black', 'orange'),
  Cursor = { reverse = true },
  lCursor = { link = 'Cursor' },
  CursorIM = { link = 'Cursor' },
  CursorColumn = hl(nil, 'selection_bg'),
  CursorLine = hl(nil, 'selection_bg'),
  Directory = hl('cyan'),
  DiffAdd = hl('added_fg', 'added_bg'),
  DiffChange = hl('changed_fg', 'changed_bg'),
  DiffDelete = hl('removed_fg', 'removed_bg'),
  DiffText = hl('black', 'blue'),
  EndOfBuffer = { link = 'NonText' },
  TermCursor = { link = 'Cursor' },
  ErrorMsg = hl('white', 'error_bg'),
  WinSeparator = { link = 'Normal' },
  Folded = hl('gray'),
  FoldColumn = { link = 'SignColumn' },
  SignColumn = { link = 'LineNr' },
  IncSearch = { link = 'CurSearch' },
  Substitute = { link = 'Search' },
  LineNr = hl('yellow'),
  LineNrAbove = { link = 'LineNr' },
  LineNrBelow = { link = 'LineNr' },
  CursorLineNr = hl('yellow', nil, { bold = true }),
  CursorLineFold = { link = 'FoldColumn' },
  CursorLineSign = { link = 'SignColumn' },
  MatchParen = hl(nil, 'selection_bg'),
  ModeMsg = { bold = true },
  MsgArea = {},
  MsgSeparator = { link = 'StatusLine' },
  MoreMsg = hl('green'),
  NonText = hl('non_text_fg', nil, { bold = true }),
  Normal = hl('fg', 'bg'),
  NormalFloat = hl('fg', 'menu_bg'),
  FloatBorder = hl('gray'),
  FloatTitle = { link = 'Title' },
  FloatFooter = { link = 'FloatTitle' },
  NormalNC = { link = 'Normal' },
  Pmenu = hl('fg', 'menu_bg'),
  PmenuSel = hl('fg', 'selection_bg'),
  PmenuKind = { link = 'Pmenu' },
  PmenuKindSel = { link = 'PmenuSel' },
  PmenuExtra = { link = 'Pmenu' },
  PmenuExtraSel = { link = 'PmenuSel' },
  PmenuSbar = hl(nil, 'menu_bg_alt'),
  PmenuThumb = hl(nil, 'selection_bg'),
  PmenuMatch = { bold = true },
  PmenuMatchSel = { bold = true },
  ComplMatchIns = {},
  Question = hl('green'),
  QuickFixLine = hl('fg', 'selection_bg', { bold = true }),
  Search = hl('black', 'search_bg'),
  SnippetTabstop = hl(nil, 'selection_bg'),
  SpecialKey = hl('cyan'),
  SpellBad = hl('red', nil, { underline = true }),
  SpellCap = hl('cyan', nil, { underline = true }),
  SpellLocal = hl('yellow', nil, { underline = true }),
  SpellRare = hl('yellow', nil, { underline = true }),
  StatusLine = { link = 'Normal' },
  StatusLineNC = hl('gray'),
  StatusLineTerm = { link = 'StatusLine' },
  StatusLineTermNC = { link = 'StatusLineNC' },
  TabLine = { reverse = true },
  TabLineFill = { reverse = true },
  TabLineSel = { bold = true },
  Title = { bold = true },
  Visual = hl(nil, 'selection_bg'),
  VisualNOS = { link = 'Visual' },
  WarningMsg = hl('yellow'),
  Whitespace = { link = 'NonText' },
  WildMenu = { link = 'PmenuSel' },
  WinBar = { bold = true },
  WinBarNC = { link = 'WinBar' },
  Comment = hl('comment_fg'),
  Constant = hl('cyan'),
  String = hl('magenta'),
  Character = { link = 'Constant' },
  Number = { link = 'Constant' },
  Boolean = { link = 'Constant' },
  Float = { link = 'Constant' },
  Identifier = { link = 'Normal' },
  Function = { link = 'Normal' },
  Statement = hl('yellow', nil, { bold = true }),
  Conditional = { link = 'Statement' },
  Repeat = { link = 'Statement' },
  Label = { link = 'Statement' },
  Operator = { link = 'Normal' },
  Keyword = { link = 'Statement' },
  Exception = { link = 'Statement' },
  PreProc = hl('magenta'),
  Include = { link = 'PreProc' },
  Define = { link = 'PreProc' },
  Macro = { link = 'PreProc' },
  PreCondit = { link = 'PreProc' },
  Type = hl('green', nil, { bold = true }),
  StorageClass = { link = 'Type' },
  Structure = { link = 'Type' },
  Typedef = { link = 'Type' },
  Special = { link = 'Normal' },
  SpecialChar = hl('orange'),
  Tag = { link = 'Statement' },
  Delimiter = { link = 'Normal' },
  SpecialComment = hl('comment_fg', nil, { italic = true }),
  Debug = { link = 'SpecialChar' },
  Underlined = hl('fg', nil, { underline = true }),
  Ignore = { link = 'Normal' },
  Error = hl('white', 'error_bg'),
  Todo = hl('cyan', nil, { bold = true, italic = true }),
  Added = hl('green'),
  Changed = hl('cyan'),
  Removed = hl('red'),
  DiagnosticError = hl('red'),
  DiagnosticWarn = hl('orange'),
  DiagnosticInfo = hl('cyan'),
  DiagnosticHint = hl('cyan'),
  DiagnosticOk = hl('green'),
  DiagnosticVirtualTextError = { link = 'DiagnosticError' },
  DiagnosticVirtualTextWarn = { link = 'DiagnosticWarn' },
  DiagnosticVirtualTextInfo = { link = 'DiagnosticInfo' },
  DiagnosticVirtualTextHint = { link = 'DiagnosticHint' },
  DiagnosticVirtualTextOk = { link = 'DiagnosticOk' },
  DiagnosticUnderlineError = hl('red', nil, { sp = 'red', underline = true }),
  DiagnosticUnderlineWarn = hl('orange', nil, { sp = 'orange', underline = true }),
  DiagnosticUnderlineInfo = hl('cyan', nil, { sp = 'cyan', underline = true }),
  DiagnosticUnderlineHint = hl('cyan', nil, { sp = 'cyan', underline = true }),
  DiagnosticUnderlineOk = hl('green', nil, { sp = 'green', underline = true }),
  DiagnosticFloatingError = { link = 'DiagnosticError' },
  DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
  DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
  DiagnosticFloatingHint = { link = 'DiagnosticHint' },
  DiagnosticFloatingOk = { link = 'DiagnosticOk' },
  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticSignWarn = { link = 'DiagnosticWarn' },
  DiagnosticSignInfo = { link = 'DiagnosticInfo' },
  DiagnosticSignHint = { link = 'DiagnosticHint' },
  DiagnosticSignOk = { link = 'DiagnosticOk' },
  DiagnosticDeprecated = { strikethrough = true },
  DiagnosticUnnecessary = { link = 'Comment' },
  ['@variable'] = { link = 'Identifier' },
  ['@variable.builtin'] = { link = 'Identifier' },
  ['@variable.parameter'] = { link = 'Identifier' },
  ['@variable.parameter.builtin'] = { link = 'Identifier' },
  ['@variable.member'] = { link = 'Identifier' },
  ['@constant'] = { link = 'Constant' },
  ['@constant.builtin'] = { link = 'Constant' },
  ['@constant.macro'] = { link = 'Macro' },
  ['@module'] = { link = 'Structure' },
  ['@module.builtin'] = { link = 'SpecialChar' },
  ['@label'] = { link = 'Label' },
  ['@string'] = { link = 'String' },
  ['@string.documentation'] = { link = 'String' },
  ['@string.regexp'] = { link = 'SpecialChar' },
  ['@string.escape'] = { link = 'SpecialChar' },
  ['@string.special'] = { link = 'SpecialChar' },
  ['@string.special.symbol'] = { link = 'SpecialChar' },
  ['@string.special.path'] = { link = 'SpecialChar' },
  ['@string.special.url'] = { link = 'Underlined' },
  ['@character'] = { link = 'Character' },
  ['@character.special'] = { link = 'SpecialChar' },
  ['@boolean'] = { link = 'Boolean' },
  ['@number'] = { link = 'Number' },
  ['@number.float'] = { link = 'Float' },
  ['@type'] = { link = 'Type' },
  ['@type.builtin'] = { link = 'Type' },
  ['@type.definition'] = { link = 'Typedef' },
  ['@type.qualifier'] = { link = 'Type' },
  ['@attribute'] = { link = 'Macro' },
  ['@attribute.builtin'] = { link = 'Macro' },
  ['@property'] = { link = 'Identifier' },
  ['@function'] = { link = 'Function' },
  ['@function.builtin'] = { link = 'Function' },
  ['@function.call'] = { link = 'Function' },
  ['@function.macro'] = { link = 'Macro' },
  ['@function.method'] = { link = 'Function' },
  ['@function.method.call'] = { link = 'Function' },
  ['@constructor'] = { link = 'Normal' },
  ['@operator'] = { link = 'Operator' },
  ['@keyword'] = { link = 'Keyword' },
  ['@keyword.coroutine'] = { link = 'Keyword' },
  ['@keyword.function'] = { link = 'Keyword' },
  ['@keyword.operator'] = { link = 'Operator' },
  ['@keyword.import'] = { link = 'Include' },
  ['@keyword.type'] = { link = 'Type' },
  ['@keyword.modifier'] = { link = 'Keyword' },
  ['@keyword.repeat'] = { link = 'Repeat' },
  ['@keyword.return'] = { link = 'Keyword' },
  ['@keyword.debug'] = { link = 'Keyword' },
  ['@keyword.exception'] = { link = 'Keyword' },
  ['@keyword.conditional'] = { link = 'Conditional' },
  ['@keyword.conditional.ternary'] = { link = 'Operator' },
  ['@keyword.directive'] = { link = 'PreProc' },
  ['@keyword.directive.define'] = { link = 'Define' },
  ['@punctuation.delimiter'] = { link = 'Delimiter' },
  ['@punctuation.bracket'] = { link = 'Normal' },
  ['@punctuation.special'] = { link = 'SpecialChar' },
  ['@comment'] = { link = 'Comment' },
  ['@comment.documentation'] = { link = 'Comment' },
  ['@comment.error'] = { link = 'DiagnosticError' },
  ['@comment.warning'] = { link = 'DiagnosticWarn' },
  ['@comment.todo'] = { link = 'Todo' },
  ['@comment.note'] = { link = 'DiagnosticInfo' },
  ['@markup.strong'] = { bold = true },
  ['@markup.italic'] = { italic = true },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.underline'] = { underline = true },
  ['@markup.heading'] = hl('cyan', nil, { bold = true }),
  ['@markup.quote'] = hl('orange'),
  ['@markup.math'] = hl('orange'),
  ['@markup.link'] = hl('cyan'),
  ['@markup.link.label'] = hl('cyan'),
  ['@markup.link.url'] = hl('cyan', nil, { underline = true, italic = true }),
  ['@markup.raw'] = hl('comment_fg'),
  ['@markup.raw.block'] = { link = 'Normal' },
  ['@markup.list'] = hl('magenta'),
  ['@markup.list.checked'] = hl('green'),
  ['@markup.list.unchecked'] = hl('gray'),
  ['@diff.plus'] = { link = 'Added' },
  ['@diff.minus'] = { link = 'Removed' },
  ['@diff.delta'] = { link = 'Changed' },
  ['@tag'] = { link = 'Tag' },
  ['@tag.builtin'] = { link = 'Tag' },
  ['@tag.attribute'] = { link = 'Type' },
  ['@tag.delimiter'] = { link = 'Normal' },
}

if vim.g.colors_name then
  vim.cmd.highlight('clear')
  vim.cmd.syntax('reset')
end
vim.g.colors_name = 'rycolor'

for group, parameters in pairs(groups) do
  vim.api.nvim_set_hl(0, group, parameters)
end

vim.api.nvim_create_autocmd('FileType', {
  callback = function()
    if vim.bo.buftype ~= '' then
      return
    end
    vim.cmd.match('ColorColumn /\\%>79v.*\\%<81v/')
  end,
})
