bind C-l last-window
set -sg escape-time 0
set -as terminal-features ',alacritty:RGB'
set -g status-style fg=#646370
set -g status-left ''
set -g status-right ''
set -g window-status-current-style fg=blue
set -g window-status-current-format '#I:#W'
set -g window-status-format '#I:#W'
